function Spectra_Wavelength_Macro(X1, Y1)

%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 04-Jan-2017 16:26:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem
stem(X1,Y1,'Marker','.','LineWidth',1,'Color',[0 0 0]);

% Create xlabel
xlabel('Wavelength (nm)');

% Create ylabel
ylabel({'Relative Intensity',''});

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[350 1100]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Palatino Linotype','FontWeight','bold');
