%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Dec-2016 09:32:02

% Create figure

function Random_Matrix_Save_Macro(Y1,filename)

figure1 = figure('Visible','off');

% Create axes
axes1 = axes('Parent',figure1,...
    'FontName','palatino linotype',...
    'Position',[0.0583267479549314 0.10387323943662 0.894162613747196 0.805281690140842]);
hold(axes1,'on');

axes1.XAxis.TickDirection='out';
axes1.YAxis.TickDirection='out';

% Create plot
plot(Y1,'ZDataSource','','Marker','.','Color',[0 0 0]);

% Create xlabel
xlabel('Domain');

% Create ylabel
ylabel({'Amplitude',''});

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 2048]);
box(axes1,'on');

%Set image size:
set(gcf,'PaperUnits','inches','PaperPosition',[0 0 20 8]);

% Set the remaining axes properties
set(axes1,'FontName','Palatino Linotype','FontWeight','bold');


saveas(figure1, [filename '.jpg']);

%print(figure1,'-dbmp',[filename '.bmp'] , '-r600');

%clf & close(gcf) clear & close the current figure, respectively.  This is
%FUCKING NECESSARY! here & in any called functions involving images, to avoid
%maxing out RAM.  The reduction was +40% in Histograms_Folder.  Here they've been placed following image saving & by trial & error. 
%Incorrect placement results in large RAM spikes.  The clear all command
%results in the same problem, or just additional memory use.  Maybe functions
%are cleared that shouldn't be- or who knows what.    

clf
close(gcf)

end
