
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Dec-2016 15:02:27

function Fourier_Transform_Macro_Stem_Save(Y1,filename,index)

% Create figure
figure1 = figure('Visible','off');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

if strcmp(index,'0')
    % Create plot
    stem(0:length(Y1)-1,Y1,...
    'Marker','.','LineWidth',1,'Color',[0 0 0]);
else
    % Create plot
    stem(Y1,'Marker','.','LineWidth',1,'Color',[0 0 0]);
end

% Create stem


% Create xlabel
xlabel('Wavenumber (A.U.)');

% Create ylabel
ylabel({'Relative Intensity',''});

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 40]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Palatino Linotype','FontWeight','bold');

saveas(figure1, [filename '.jpg']);

%print(figure1,'-dbmp',[filename '.bmp'] , '-r600');

clf
close(gcf)

end


