
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Dec-2016 15:02:27

function Fourier_Transform_Macro_Line_Save(Y1,filename,index)

% Create figure
figure1 = figure('Visible','off');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

if strcmp(index,'0')
    % Create plot
    plot(0:length(Y1)-1,Y1,...
        'MarkerFaceColor',[1 1 1],'MarkerEdgeColor',[0 0 0],'MarkerSize',10,...
        'Marker','.',...
        'Color',[0 0 0]);
else
    % Create plot
    plot(Y1,...
        'MarkerFaceColor',[1 1 1],'MarkerEdgeColor',[0 0 0],'MarkerSize',10,...
        'Marker','.',...
        'Color',[0 0 0]);
end

% Create xlabel
xlabel('Wavenumber (A.U)');

% Create ylabel
ylabel('Relative Intensity');

%axis limit
ylim(axes1,[0 0.6]);
xlim(axes1,[0 40]);


box(axes1,'on');

% Set the remaining axes properties
set(axes1,'FontName','Palatino Linotype','FontWeight','bold');

saveas(figure1, [filename '.jpg']);

%print(figure1,'-dbmp',[filename '.bmp'] , '-r600');

clf
close(gcf)

end


