function Fourier_Transform_Macro_Complex_Save(Y1,filename,index)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 04-Jan-2017 19:52:39

% Create figure
figure1 = figure('Visible','off');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1,'Color',[0 0 0]);

% Create xlabel
xlabel('R');

% Create ylabel
ylabel('C');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontWeight','bold');

xlim(axes1,[-.3 .3]);
ylim(axes1,[-.3 .3]);

saveas(figure1, [filename '.jpg']);

%print(figure1,'-dbmp',[filename '.bmp'] , '-r600');

clf
close(gcf)

end
